import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../app/global.css'
import Navbar from '../components/Header'
import { cn } from '@/lib/utils'
import React from 'react'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(" h-full font-sans ",inter.className)}>
        <main className=' flex flex-col min-h-screen'>
        <Providers>
        <Navbar/>
          <div className=''>
          {children}
          </div></Providers>
        </main>
        <Toaster position='top-center' richColors/>
       </body>
    </html>
  )
}
